output   = "db/models"
wipe     = true
no-tests = true
add-enum-types = true
add-global-variants=true

[mysql]
dbname = "hackernews"
host = "localhost"
port = 3306
user = "root"
pass = "root1234"
sslmode = "false"

[auto-columns]
updated = "modified_at"
