// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Employee         string
	SchemaMigrations string
	User             string
}{
	Employee:         "employee",
	SchemaMigrations: "schema_migrations",
	User:             "user",
}
